// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{        
    public class BuffTabelLib:DBFItemBase
    {        
        public enum BuffType
        {
            /// <summary>威力</summary>
            Type1 = 0x01,
            /// <summary>連擊力</summary>
            Type2,
            /// <summary>觀察力</summary>
            Type3,
            /// <summary>投資</summary>
            Type4,
            /// <summary>挑釁語句</summary>
            Type5,

        }
        /// <summary>名稱</summary>
        public string Name = "";
        /// <summary>等級</summary>
        public int Lv = 1;
        /// <summary>說明</summary>
        public string Tip = "";
    }
}
