// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{        
    public class ChallengeStageLib:DBFItemBase
    {        
        public class Require
        {
            public int ItemID = -1;
            public int Value = 0;
        }

        public class GateInfo
        {
            public int NpcID = -1;
            public int Weight = 0;
        }
        
        public class ExpInfo
        {
            public int Win = 0;
            public int Lose = 0;
            public int Tie = 0;
        }

        /// <summary>名稱</summary>
        public string NAME = "";
        /// <summary>難度設定</summary>
        public int Degree = 0;
        /// <summary>時間</summary>
        public int TimeLimit = 0;
        /// <summary>入場道具</summary>
        public Require RequireItem = new Require();
        /// <summary>過關獲得分數</summary>
        public int Score = 0;
        /// <summary>關主代號</summary>
        public int BOSS = 0;
        /// <summary>通關經驗值資訊</summary>
        public ExpInfo Exp;

        public GateInfo[] Appear = { };

        public int GetGameExp(int result)
        {
            int exp = 0;

            switch(result)
            {
                case 0:
                    exp = Exp.Lose;
                    break;
                case 1:
                    exp = Exp.Win;
                    break;
                case 2:
                    exp = Exp.Tie;
                    break;
            }

            return exp;
        }
    }
}
