// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{        
    public class ChallengeNpcLib:DBFItemBase
    {        
        /// <summary>名稱</summary>
        public string Name = "";
        /// <summary>頭像</summary>
        public string Pic = "";        
        /// <summary>石頭ID</summary>
        public int ItemID = -1;
    }
}
