// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{        
    public class ConfigLib:DBFItemBase
    {        
        /// <summary>
        /// 角色抽獎所需道具資訊
        /// </summary>
        public class ItemInfo
        {
            public int ItemID = -1;
            public int Value = 0;
        }

        /// <summary>初始遊戲幣</summary>
        public int DefaultCoin = 0;
        /// <summary>初始商城幣</summary>
        public int DefaultGold = 0;
        /// <summary>預設擁有角色代號</summary>
        public int DefaultRole = 0;
        /// <summary>預設擁有BUFF</summary>
        public int[] DefaultBuff = {};
        /// <summary>角色最大等級</summary>
        public int RoleMaxLv = 0;        
        /// <summary>角色抽獎所需道具資訊</summary>
        public ItemInfo lotteryRole = null;
        public int MaxLv = 1;
    }
}
