// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{    
    public class ItemBaseData:DBFItemBase
    {
        public int Type;

        public string Name;

        public string Act = "-1";

        public int Flag;
    }
}
