// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{    
    public class ItemRoleValueData:ItemBaseData
    {
        public int Max = 1;
        public string ClientVar = "";
    }
}
