// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{        
    public class QuestionLib:DBFItemBase
    {        
        public enum QuestionType
        {
            YorN = 0x01,
            Choose,
            Sort,
        }

        /// <summary>類型</summary>
        public int Type = (int)QuestionType.Choose;
        /// <summary>分類</summary>
        public int Catalog = 1;
        /// <summary>難易度</summary>
        public int Difficult = 1;
        
        /// <summary>題目</summary>
        public string Question = "-1";
        /// <summary>選項1</summary>
        public string Option1 = "-1";
        /// <summary>選項2</summary>
        public string Option2 = "-1";
        /// <summary>選項3</summary>
        public string Option3 = "-1";
        /// <summary>選項4</summary>
        public string Option4 = "-1";

    }
}
