// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{        
    public class RoleConfigLib:DBFItemBase
    {
        public class RewardInfo
        {
            public int ItemID = -1;
            public int Value = 0;
        }

        /// <summary>需求經驗值</summary>
        public int Exp;
        
        /// <summary>血量</summary>
        public int HP;
        
        /// <summary>獎勵資訊</summary>
        public RewardInfo[] Reward = null;
    }
}
