// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{        
    public class SchoolLib:DBFItemBase
    {        
        /// <summary>類型</summary>
        public int Type = 0;
        /// <summary>名稱</summary>
        public string Name = "";
        /// <summary>圖</summary>
        public string Pic = "";
    }
}
