// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;

namespace Model.DBF
{        
    public class ShopLib:DBFItemBase
    {        
        /// <summary>類型</summary>
        public int Type = 0;
        /// <summary>SkuID</summary>
        public string SkuID = "";
        /// <summary>獲得道具編號</summary>
        public int ItemID = 0;
        /// <summary>獲得數量</summary>
        public int Value = 0;
        /// <summary>花費</summary>
        public int Pay = 0;
        /// <summary>是否優惠中 0:無 1:有</summary>
        public int OnSale = 0;
    }
}
